import type { ReferenceItem } from "./types";

export const REFERENCE_ITEMS: ReferenceItem[] = [
  {
    id: "coffee",
    name: "coffee",
    price: 5,
    frequency: "one-time",
    category: "food",
  },
  {
    id: "fast-food-meal",
    name: "fast food meal",
    price: 10,
    frequency: "one-time",
    category: "food",
  },
  {
    id: "nice-dinner",
    name: "nice dinner out",
    price: 40,
    frequency: "one-time",
    category: "food",
  },
  {
    id: "movie-ticket",
    name: "movie ticket",
    price: 15,
    frequency: "one-time",
    category: "entertainment",
  },
  {
    id: "concert-ticket",
    name: "concert ticket",
    price: 80,
    frequency: "one-time",
    category: "entertainment",
  },
  {
    id: "netflix",
    name: "Netflix subscription",
    price: 15,
    frequency: "monthly",
    category: "entertainment",
  },
  {
    id: "gym-membership",
    name: "gym membership",
    price: 40,
    frequency: "monthly",
    category: "lifestyle",
  },
  {
    id: "spotify",
    name: "Spotify subscription",
    price: 10,
    frequency: "monthly",
    category: "entertainment",
  },
  {
    id: "ps5",
    name: "PS5",
    price: 500,
    frequency: "one-time",
    category: "tech",
  },
  {
    id: "iphone",
    name: "iPhone",
    price: 999,
    frequency: "one-time",
    category: "tech",
  },
  {
    id: "laptop",
    name: "laptop",
    price: 1200,
    frequency: "one-time",
    category: "tech",
  },
  {
    id: "domestic-flight",
    name: "domestic flight",
    price: 300,
    frequency: "one-time",
    category: "travel",
  },
  {
    id: "international-flight",
    name: "international flight",
    price: 800,
    frequency: "one-time",
    category: "travel",
  },
  {
    id: "rent",
    name: "rent",
    price: 1500,
    frequency: "monthly",
    category: "lifestyle",
  },
  {
    id: "utilities",
    name: "utilities (electric/water/internet)",
    price: 200,
    frequency: "monthly",
    category: "utilities",
  },
];
